export default [
   {
      "author": "Chinua Achebe",
      "country": "Nigeria",
      "imageLink": "images/things-fall-apart.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart",
      "pages": 209,
      "title": "Things Fall Apart",
      "year": 1958,
      "id": "uafftFaAg7vTxvHTVmezDCpWE7ES3UkK"
   },
   {
      "author": "Hans Christian Andersen",
      "country": "Denmark",
      "imageLink": "images/fairy-tales.jpg",
      "language": "Danish",
      "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.",
      "pages": 784,
      "title": "Fairy tales",
      "year": 1836,
      "id": "F7TmpErVPmCA8Q5iG0t5sGwbXssze4kg"
   },
   {
      "author": "Dante Alighieri",
      "country": "Italy",
      "imageLink": "images/the-divine-comedy.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy",
      "pages": 928,
      "title": "The Divine Comedy",
      "year": 1315,
      "id": "slA0HAVwI2mrUzGZ6hdj7LBN86WDIxVB"
   },
   {
      "author": "Unknown",
      "country": "India/Iran/Iraq/Egypt/Tajikistan",
      "imageLink": "images/one-thousand-and-one-nights.jpg",
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights",
      "pages": 288,
      "title": "One Thousand and One Nights",
      "year": 1200,
      "id": "t7cHOcpV2OotjvHV1Sfe_mltgcwBkRhT"
   },
   {
      "author": "Jane Austen",
      "country": "United Kingdom",
      "imageLink": "images/pride-and-prejudice.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
      "pages": 226,
      "title": "Pride and Prejudice",
      "year": 1813,
      "id": "O2X6pXTCrGjAnlttxfHcVKtQ8B0ZJmuV"
   },
   {
      "author": "Honoré de Balzac",
      "country": "France",
      "imageLink": "images/le-pere-goriot.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot",
      "pages": 443,
      "title": "Le Père Goriot",
      "year": 1835,
      "id": "jyIm3u4H54sEIjWNNdb9f3CLoQAJwt15"
   },
   {
      "author": "Samuel Beckett",
      "country": "Republic of Ireland",
      "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
      "language": "French, English",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)",
      "pages": 256,
      "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
      "year": 1952,
      "id": "kWbzMd8Q_Q3elXIHKatxuImNScPLDY0j"
   },
   {
      "author": "Giovanni Boccaccio",
      "country": "Italy",
      "imageLink": "images/the-decameron.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/The_Decameron",
      "pages": 1024,
      "title": "The Decameron",
      "year": 1351,
      "id": "csDI78SMXE1X2DlLbBx51eh0rdcAckPz"
   },
   {
      "author": "Jorge Luis Borges",
      "country": "Argentina",
      "imageLink": "images/ficciones.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Ficciones",
      "pages": 224,
      "title": "Ficciones",
      "year": 1965,
      "id": "fplduVhSy1B8kjtPMdIkfIaSuRl5wTLY"
   },
   {
      "author": "Emily Brontë",
      "country": "United Kingdom",
      "imageLink": "images/wuthering-heights.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Wuthering_Heights",
      "pages": 342,
      "title": "Wuthering Heights",
      "year": 1847,
      "id": "KMV0a0SeZbvqjkSkk43Cn7ozIZ9DwYHG"
   },
   {
      "author": "Albert Camus",
      "country": "Algeria, French Empire",
      "imageLink": "images/l-etranger.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)",
      "pages": 185,
      "title": "The Stranger",
      "year": 1942,
      "id": "VMLokHO1T6mI1bwSq5FuckKM6_jYi562"
   },
   {
      "author": "Paul Celan",
      "country": "Romania, France",
      "imageLink": "images/poems-paul-celan.jpg",
      "language": "German",
      "link": "",
      "pages": 320,
      "title": "Poems",
      "year": 1952,
      "id": "P_wTxUiUo85dEL5S0RGs1E7CNDvllvbo"
   },
   {
      "author": "Louis-Ferdinand Céline",
      "country": "France",
      "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night",
      "pages": 505,
      "title": "Journey to the End of the Night",
      "year": 1932,
      "id": "FD4qqGBxiKOulvZwwsb_YQEHQQH7ev1j"
   },
   {
      "author": "Miguel de Cervantes",
      "country": "Spain",
      "imageLink": "images/don-quijote-de-la-mancha.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Don_Quixote",
      "pages": 1056,
      "title": "Don Quijote De La Mancha",
      "year": 1610,
      "id": "8iwlqKuUuQKAUciFqlxpGjagnSFeGOH4"
   },
   {
      "author": "Geoffrey Chaucer",
      "country": "England",
      "imageLink": "images/the-canterbury-tales.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales",
      "pages": 544,
      "title": "The Canterbury Tales",
      "year": 1450,
      "id": "pVKeSILEEX88SAn_qieuwvIyYm7kmiwR"
   },
   {
      "author": "Anton Chekhov",
      "country": "Russia",
      "imageLink": "images/stories-of-anton-chekhov.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov",
      "pages": 194,
      "title": "Stories",
      "year": 1886,
      "id": "jnsTTHwwV7icXPEmh8ZV7PnOb52Qp8nq"
   },
   {
      "author": "Joseph Conrad",
      "country": "United Kingdom",
      "imageLink": "images/nostromo.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Nostromo",
      "pages": 320,
      "title": "Nostromo",
      "year": 1904,
      "id": "WYTMuMysLOtEGlH6bK7I5O3VHppQRinq"
   },
   {
      "author": "Charles Dickens",
      "country": "United Kingdom",
      "imageLink": "images/great-expectations.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Great_Expectations",
      "pages": 194,
      "title": "Great Expectations",
      "year": 1861,
      "id": "jmHHjYi7XbthRwW9dB7QnRZJRlEtj7JP"
   },
   {
      "author": "Denis Diderot",
      "country": "France",
      "imageLink": "images/jacques-the-fatalist.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist",
      "pages": 596,
      "title": "Jacques the Fatalist",
      "year": 1796,
      "id": "KMBm_6eO3vHNRohsoV7KChBhoeUETvqx"
   },
   {
      "author": "Alfred Döblin",
      "country": "Germany",
      "imageLink": "images/berlin-alexanderplatz.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz",
      "pages": 600,
      "title": "Berlin Alexanderplatz",
      "year": 1929,
      "id": "jY5Sjd1R0irZNpCUguMMCP1zjh9I12XG"
   },
   {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/crime-and-punishment.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment",
      "pages": 551,
      "title": "Crime and Punishment",
      "year": 1866,
      "id": "shxH9iHF6GADSGem5uU03xaKrHr38Uz6"
   },
   {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-idiot.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Idiot",
      "pages": 656,
      "title": "The Idiot",
      "year": 1869,
      "id": "8e5K6W8K298wSqLYVGCANbiJplWMzJPY"
   },
   {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-possessed.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)",
      "pages": 768,
      "title": "The Possessed",
      "year": 1872,
      "id": "QYjT3dl1vIJt_khkzg3QWkApUli054Ia"
   },
   {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-brothers-karamazov.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov",
      "pages": 824,
      "title": "The Brothers Karamazov",
      "year": 1880,
      "id": "ik5WyVSSsvlKv3zTUjRSlWy3uIohxQgZ"
   },
   {
      "author": "George Eliot",
      "country": "United Kingdom",
      "imageLink": "images/middlemarch.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Middlemarch",
      "pages": 800,
      "title": "Middlemarch",
      "year": 1871,
      "id": "gOM3DqRGgHuBP3SGqZ0wVodkV3KicR0E"
   },
   {
      "author": "Ralph Ellison",
      "country": "United States",
      "imageLink": "images/invisible-man.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Invisible_Man",
      "pages": 581,
      "title": "Invisible Man",
      "year": 1952,
      "id": "TrDLIXUcWpah3Bb4ifF6ETFM0XEGLwNe"
   },
   {
      "author": "Euripides",
      "country": "Greece",
      "imageLink": "images/medea.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Medea_(play)",
      "pages": 104,
      "title": "Medea",
      "year": -431,
      "id": "Wmq7cQktVjT0MuIqjVBt0G1ZS5LdWygt"
   },
   {
      "author": "William Faulkner",
      "country": "United States",
      "imageLink": "images/absalom-absalom.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!",
      "pages": 313,
      "title": "Absalom, Absalom!",
      "year": 1936,
      "id": "7WGletDUDtYzR2UBO4dOwuR8p6yc34z5"
   },
   {
      "author": "William Faulkner",
      "country": "United States",
      "imageLink": "images/the-sound-and-the-fury.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury",
      "pages": 326,
      "title": "The Sound and the Fury",
      "year": 1929,
      "id": "e9bQlhIBLlNFJL0SmgKufPXFQvvF46s8"
   },
   {
      "author": "Gustave Flaubert",
      "country": "France",
      "imageLink": "images/madame-bovary.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Madame_Bovary",
      "pages": 528,
      "title": "Madame Bovary",
      "year": 1857,
      "id": "UKZ5pMP8Y25uVm7GtayQLbl1UCm20QRG"
   },
   {
      "author": "Gustave Flaubert",
      "country": "France",
      "imageLink": "images/l-education-sentimentale.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Sentimental_Education",
      "pages": 606,
      "title": "Sentimental Education",
      "year": 1869,
      "id": "kqnEVklagsIJeGp_A9HnyQtSZrcVD7pQ"
   },
   {
      "author": "Federico García Lorca",
      "country": "Spain",
      "imageLink": "images/gypsy-ballads.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Gypsy_Ballads",
      "pages": 218,
      "title": "Gypsy Ballads",
      "year": 1928,
      "id": "0AwGAtK0unxiCF05fsXyTCOltFjhNIM_"
   },
   {
      "author": "Gabriel García Márquez",
      "country": "Colombia",
      "imageLink": "images/one-hundred-years-of-solitude.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude",
      "pages": 417,
      "title": "One Hundred Years of Solitude",
      "year": 1967,
      "id": "Dnf5YwBVjNt52eOQRYUKNkgcS8uclVwA"
   },
   {
      "author": "Gabriel García Márquez",
      "country": "Colombia",
      "imageLink": "images/love-in-the-time-of-cholera.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera",
      "pages": 368,
      "title": "Love in the Time of Cholera",
      "year": 1985,
      "id": "XZ8fG1ISoBeKTub5SGWgIrxv7VzTTOsq"
   },
   {
      "author": "Johann Wolfgang von Goethe",
      "country": "Saxe-Weimar",
      "imageLink": "images/faust.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust",
      "pages": 158,
      "title": "Faust",
      "year": 1832,
      "id": "L6heRKBOjbK9VHgZOLAQAn2vDK_IbgkL"
   },
   {
      "author": "Nikolai Gogol",
      "country": "Russia",
      "imageLink": "images/dead-souls.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Dead_Souls",
      "pages": 432,
      "title": "Dead Souls",
      "year": 1842,
      "id": "9BT11JMu7bWGmY_Gwxw0lrCOmKjPyDRk"
   },
   {
      "author": "Günter Grass",
      "country": "Germany",
      "imageLink": "images/the-tin-drum.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Tin_Drum",
      "pages": 600,
      "title": "The Tin Drum",
      "year": 1959,
      "id": "hLTqb7m1gLlSWGwUNNSELcPD0QBOzrtd"
   },
   {
      "author": "João Guimarães Rosa",
      "country": "Brazil",
      "imageLink": "images/the-devil-to-pay-in-the-backlands.jpg",
      "language": "Portuguese",
      "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands",
      "pages": 494,
      "title": "The Devil to Pay in the Backlands",
      "year": 1956,
      "id": "xrLOvK99M0RsKacaCpCbEI2GpafPLGK9"
   },
   {
      "author": "Knut Hamsun",
      "country": "Norway",
      "imageLink": "images/hunger.jpg",
      "language": "Norwegian",
      "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)",
      "pages": 176,
      "title": "Hunger",
      "year": 1890,
      "id": "wYhpFUGxFG_gU0a3Xj4vvL6AV0__pgXE"
   },
   {
      "author": "Ernest Hemingway",
      "country": "United States",
      "imageLink": "images/the-old-man-and-the-sea.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea",
      "pages": 128,
      "title": "The Old Man and the Sea",
      "year": 1952,
      "id": "7LE7WKpynH3jhiPeL1HTVCKzkfADiJsY"
   },
   {
      "author": "Homer",
      "country": "Greece",
      "imageLink": "images/the-iliad-of-homer.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Iliad",
      "pages": 608,
      "title": "Iliad",
      "year": -735,
      "id": "2bnQak4euWoTsaWo8NWalCSpb7NOXoW4"
   },
   {
      "author": "Homer",
      "country": "Greece",
      "imageLink": "images/the-odyssey-of-homer.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Odyssey",
      "pages": 374,
      "title": "Odyssey",
      "year": -800,
      "id": "TIWae6Mpmdj4_hBrvy9ZjDEeTKSxH1El"
   },
   {
      "author": "Henrik Ibsen",
      "country": "Norway",
      "imageLink": "images/a-Dolls-house.jpg",
      "language": "Norwegian",
      "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House",
      "pages": 68,
      "title": "A Doll's House",
      "year": 1879,
      "id": "l9hkCTCOC6b6JEjjmjVhKWIXNVBBtqCF"
   },
   {
      "author": "James Joyce",
      "country": "Irish Free State",
      "imageLink": "images/ulysses.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)",
      "pages": 228,
      "title": "Ulysses",
      "year": 1922,
      "id": "Lr7mqtZrOv807UNHEf7tByD5WlcCk81I"
   },
   {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/stories-of-franz-kafka.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories",
      "pages": 488,
      "title": "Stories",
      "year": 1924,
      "id": "RwGmUchKw3v9FVdVoXUNO8U6QH7VGSlf"
   },
   {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/the-trial.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Trial",
      "pages": 160,
      "title": "The Trial",
      "year": 1925,
      "id": "bsjq82Me6I6HkLziRh_d3kefd3NxRXex"
   },
   {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/the-castle.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)",
      "pages": 352,
      "title": "The Castle",
      "year": 1926,
      "id": "DS56hN92WmF0h8MqqPjM5rGSMz1lNXnd"
   },
   {
      "author": "Kālidāsa",
      "country": "India",
      "imageLink": "images/the-recognition-of-shakuntala.jpg",
      "language": "Sanskrit",
      "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam",
      "pages": 147,
      "title": "The recognition of Shakuntala",
      "year": 150,
      "id": "BCxJqgJa2gQs4DE3MkbmKRiESkZ8kjty"
   },
   {
      "author": "Yasunari Kawabata",
      "country": "Japan",
      "imageLink": "images/the-sound-of-the-mountain.jpg",
      "language": "Japanese",
      "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain",
      "pages": 288,
      "title": "The Sound of the Mountain",
      "year": 1954,
      "id": "nvJD6TTyTfXcKqPWA3qDaCgaWiMdngnr"
   },
   {
      "author": "Nikos Kazantzakis",
      "country": "Greece",
      "imageLink": "images/zorba-the-greek.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Zorba_the_Greek",
      "pages": 368,
      "title": "Zorba the Greek",
      "year": 1946,
      "id": "kq0QWIdzlyiPPxeudhbw06ekitsXzc3Y"
   },
   {
      "author": "D. H. Lawrence",
      "country": "United Kingdom",
      "imageLink": "images/sons-and-lovers.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers",
      "pages": 432,
      "title": "Sons and Lovers",
      "year": 1913,
      "id": "CIRZ9iFhlowU8rpVGel5V0b4P91b3v_4"
   },
   {
      "author": "Halldór Laxness",
      "country": "Iceland",
      "imageLink": "images/independent-people.jpg",
      "language": "Icelandic",
      "link": "https://en.wikipedia.org/wiki/Independent_People",
      "pages": 470,
      "title": "Independent People",
      "year": 1934,
      "id": "n0ejLtfhT5e1A1Sn3sGKeftwskrwiQ8G"
   },
   {
      "author": "Giacomo Leopardi",
      "country": "Italy",
      "imageLink": "images/poems-giacomo-leopardi.jpg",
      "language": "Italian",
      "link": "",
      "pages": 184,
      "title": "Poems",
      "year": 1818,
      "id": "3ohDFwJtS7xnY087tytOmrBOhldw6R_z"
   },
   {
      "author": "Doris Lessing",
      "country": "United Kingdom",
      "imageLink": "images/the-golden-notebook.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Golden_Notebook",
      "pages": 688,
      "title": "The Golden Notebook",
      "year": 1962,
      "id": "ssKm5BsDIqREGtaGLqBKX_Pj15dC0QA4"
   },
   {
      "author": "Astrid Lindgren",
      "country": "Sweden",
      "imageLink": "images/pippi-longstocking.jpg",
      "language": "Swedish",
      "link": "https://en.wikipedia.org/wiki/Pippi_Longstocking",
      "pages": 160,
      "title": "Pippi Longstocking",
      "year": 1945,
      "id": "eYW6wi1MWdiEzPopy1fsBLaHo6OUOUgm"
   },
   {
      "author": "Lu Xun",
      "country": "China",
      "imageLink": "images/diary-of-a-madman.jpg",
      "language": "Chinese",
      "link": "https://en.wikipedia.org/wiki/A_Madman%27s_Diary",
      "pages": 389,
      "title": "Diary of a Madman",
      "year": 1918,
      "id": "alUS9E7i8aTVibkMJ2B6T6dhvx0HsxA1"
   },
   {
      "author": "Naguib Mahfouz",
      "country": "Egypt",
      "imageLink": "images/children-of-gebelawi.jpg",
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/Children_of_Gebelawi",
      "pages": 355,
      "title": "Children of Gebelawi",
      "year": 1959,
      "id": "TjY4IzbO90SIVz_OaKn92Yfs70aBI50k"
   },
   {
      "author": "Thomas Mann",
      "country": "Germany",
      "imageLink": "images/buddenbrooks.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Buddenbrooks",
      "pages": 736,
      "title": "Buddenbrooks",
      "year": 1901,
      "id": "hPJ0IWCMwuJsy8TOcbQcgMt9xsC4ZLj4"
   },
   {
      "author": "Thomas Mann",
      "country": "Germany",
      "imageLink": "images/the-magic-mountain.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Magic_Mountain",
      "pages": 720,
      "title": "The Magic Mountain",
      "year": 1924,
      "id": "x8gzYz1gv9WPVut3wGV1dWFvaAvNXLzE"
   },
   {
      "author": "Herman Melville",
      "country": "United States",
      "imageLink": "images/moby-dick.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Moby-Dick",
      "pages": 378,
      "title": "Moby Dick",
      "year": 1851,
      "id": "QSP6NOAt16EtZxF7bznNxpt1Q064iP8M"
   },
   {
      "author": "Michel de Montaigne",
      "country": "France",
      "imageLink": "images/essais.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)",
      "pages": 404,
      "title": "Essays",
      "year": 1595,
      "id": "rpBTmWyZOloRY9apQUqA5LJ0sg8E4s7_"
   },
   {
      "author": "Elsa Morante",
      "country": "Italy",
      "imageLink": "images/history.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/History_(novel)",
      "pages": 600,
      "title": "History",
      "year": 1974,
      "id": "usTpuRH0zH7KcMX9Hej1ct0n3ei557cr"
   },
   {
      "author": "Toni Morrison",
      "country": "United States",
      "imageLink": "images/beloved.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Beloved_(novel)",
      "pages": 321,
      "title": "Beloved",
      "year": 1987,
      "id": "U8swDfJCI66YkDov0Zv7OJZQHpDDb64e"
   },
   {
      "author": "Murasaki Shikibu",
      "country": "Japan",
      "imageLink": "images/the-tale-of-genji.jpg",
      "language": "Japanese",
      "link": "https://en.wikipedia.org/wiki/The_Tale_of_Genji",
      "pages": 1360,
      "title": "The Tale of Genji",
      "year": 1006,
      "id": "IZ0ORoPvWGv8YhSBf7IsXJv2uTtNGOk1"
   },
   {
      "author": "Robert Musil",
      "country": "Austria",
      "imageLink": "images/the-man-without-qualities.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Man_Without_Qualities",
      "pages": 365,
      "title": "The Man Without Qualities",
      "year": 1931,
      "id": "6AprEKROoz7wKApQCXsHs_bQPAbxDmDh"
   },
   {
      "author": "Vladimir Nabokov",
      "country": "Russia/United States",
      "imageLink": "images/lolita.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Lolita",
      "pages": 317,
      "title": "Lolita",
      "year": 1955,
      "id": "Mibz14hsPpQLkCuJIcf6EoBJzWO0k_3S"
   },
   {
      "author": "George Orwell",
      "country": "United Kingdom",
      "imageLink": "images/nineteen-eighty-four.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four",
      "pages": 272,
      "title": "Nineteen Eighty-Four",
      "year": 1949,
      "id": "3OTMMmzGeTZGVxjlQPJMiEbV1OGNopm4"
   },
   {
      "author": "Ovid",
      "country": "Roman Empire",
      "imageLink": "images/the-metamorphoses-of-ovid.jpg",
      "language": "Classical Latin",
      "link": "https://en.wikipedia.org/wiki/Metamorphoses",
      "pages": 576,
      "title": "Metamorphoses",
      "year": 100,
      "id": "SWJcPzjJcixpZFCBAYpVB9x1qnajcjUm"
   },
   {
      "author": "Fernando Pessoa",
      "country": "Portugal",
      "imageLink": "images/the-book-of-disquiet.jpg",
      "language": "Portuguese",
      "link": "https://en.wikipedia.org/wiki/The_Book_of_Disquiet",
      "pages": 272,
      "title": "The Book of Disquiet",
      "year": 1928,
      "id": "C8BPakOA_OtxIbsUQuXj78vHZBg9UxuV"
   },
   {
      "author": "Edgar Allan Poe",
      "country": "United States",
      "imageLink": "images/tales-and-poems-of-edgar-allan-poe.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales",
      "pages": 842,
      "title": "Tales",
      "year": 1950,
      "id": "tFC9nVahGgSRBA8_E4ewVuS15rWyasdp"
   },
   {
      "author": "Marcel Proust",
      "country": "France",
      "imageLink": "images/a-la-recherche-du-temps-perdu.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time",
      "pages": 2408,
      "title": "In Search of Lost Time",
      "year": 1920,
      "id": "zd0Dm4SXBXDbDgCTrwJDFVpcQXay5ciV"
   },
   {
      "author": "François Rabelais",
      "country": "France",
      "imageLink": "images/gargantua-and-pantagruel.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel",
      "pages": 623,
      "title": "Gargantua and Pantagruel",
      "year": 1533,
      "id": "AO5GV6_a63oKPPONDqaQhHwBf5ABFZoR"
   },
   {
      "author": "Juan Rulfo",
      "country": "Mexico",
      "imageLink": "images/pedro-paramo.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo",
      "pages": 124,
      "title": "Pedro Páramo",
      "year": 1955,
      "id": "XM_Z8Lsr80AEM98k2NEY26r2lH8vxSUs"
   },
   {
      "author": "Rumi",
      "country": "Sultanate of Rum",
      "imageLink": "images/the-masnavi.jpg",
      "language": "Persian",
      "link": "https://en.wikipedia.org/wiki/Masnavi",
      "pages": 438,
      "title": "The Masnavi",
      "year": 1236,
      "id": "KVsiTkEf3qr_ga00Xry2PaEZ5HQiIF1J"
   },
   {
      "author": "Salman Rushdie",
      "country": "United Kingdom, India",
      "imageLink": "images/midnights-children.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Midnight%27s_Children",
      "pages": 536,
      "title": "Midnight's Children",
      "year": 1981,
      "id": "XUslMOvgLybsYuPAJj3hbxwh4D67V8W9"
   },
   {
      "author": "Saadi",
      "country": "Persia, Persian Empire",
      "imageLink": "images/bostan.jpg",
      "language": "Persian",
      "link": "https://en.wikipedia.org/wiki/Bustan_(book)",
      "pages": 298,
      "title": "Bostan",
      "year": 1257,
      "id": "KUkvebd2ayNecOcXJJhdiGx5HWB8l0S3"
   },
   {
      "author": "Tayeb Salih",
      "country": "Sudan",
      "imageLink": "images/season-of-migration-to-the-north.jpg",
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North",
      "pages": 139,
      "title": "Season of Migration to the North",
      "year": 1966,
      "id": "eE0uD6HkQdnWoob7GKbymdpIfSgDQDvr"
   },
   {
      "author": "José Saramago",
      "country": "Portugal",
      "imageLink": "images/blindness.jpg",
      "language": "Portuguese",
      "link": "https://en.wikipedia.org/wiki/Blindness_(novel)",
      "pages": 352,
      "title": "Blindness",
      "year": 1995,
      "id": "BZVj9HShK0PZkWEU70Bo5iirwBPpZxm9"
   },
   {
      "author": "William Shakespeare",
      "country": "England",
      "imageLink": "images/hamlet.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Hamlet",
      "pages": 432,
      "title": "Hamlet",
      "year": 1603,
      "id": "lVpi4uaB9b97SJCTbmzSWRtKMZ8yx9a2"
   },
   {
      "author": "William Shakespeare",
      "country": "England",
      "imageLink": "images/king-lear.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/King_Lear",
      "pages": 384,
      "title": "King Lear",
      "year": 1608,
      "id": "RN9aI1prDq1M0G6D7bIZXpByK8qCpD_i"
   },
   {
      "author": "William Shakespeare",
      "country": "England",
      "imageLink": "images/othello.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Othello",
      "pages": 314,
      "title": "Othello",
      "year": 1609,
      "id": "l1BiAtJJB2aH8X7FH3kAXzoB7YqM98UE"
   },
   {
      "author": "Sophocles",
      "country": "Greece",
      "imageLink": "images/oedipus-the-king.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Oedipus_the_King",
      "pages": 88,
      "title": "Oedipus the King",
      "year": -430,
      "id": "KVYl401FNcONofp1WoaHI2TZlBD9Cb0Q"
   },
   {
      "author": "Stendhal",
      "country": "France",
      "imageLink": "images/le-rouge-et-le-noir.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black",
      "pages": 576,
      "title": "The Red and the Black",
      "year": 1830,
      "id": "Pm1sxxqczlMhJuEepFcinafrU_Wk7cL7"
   },
   {
      "author": "Laurence Sterne",
      "country": "England",
      "imageLink": "images/the-life-and-opinions-of-tristram-shandy.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman",
      "pages": 640,
      "title": "The Life And Opinions of Tristram Shandy",
      "year": 1760,
      "id": "bihoTfMfRZKlp3XQpltak2s6oF9E_sDK"
   },
   {
      "author": "Italo Svevo",
      "country": "Italy",
      "imageLink": "images/confessions-of-zeno.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience",
      "pages": 412,
      "title": "Confessions of Zeno",
      "year": 1923,
      "id": "ly95mpUdy3cdS6TPLGiy4WiaTXBme185"
   },
   {
      "author": "Jonathan Swift",
      "country": "Ireland",
      "imageLink": "images/gullivers-travels.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels",
      "pages": 178,
      "title": "Gulliver's Travels",
      "year": 1726,
      "id": "XxpOeVgzBW4gOG3ILJHd8EImxw5Gdfbt"
   },
   {
      "author": "Leo Tolstoy",
      "country": "Russia",
      "imageLink": "images/war-and-peace.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/War_and_Peace",
      "pages": 1296,
      "title": "War and Peace",
      "year": 1867,
      "id": "_aDnsfLP2K9yBtG_9QGJEpNZcMUsfIwE"
   },
   {
      "author": "Leo Tolstoy",
      "country": "Russia",
      "imageLink": "images/anna-karenina.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Anna_Karenina",
      "pages": 864,
      "title": "Anna Karenina",
      "year": 1877,
      "id": "Weo8WY_EEFZOq_ZNmmIjLOxWoE_2rRyq"
   },
   {
      "author": "Leo Tolstoy",
      "country": "Russia",
      "imageLink": "images/the-death-of-ivan-ilyich.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich",
      "pages": 92,
      "title": "The Death of Ivan Ilyich",
      "year": 1886,
      "id": "YzyH554wvsi5tjNCNLAl7bT427kuAizV"
   },
   {
      "author": "Mark Twain",
      "country": "United States",
      "imageLink": "images/the-adventures-of-huckleberry-finn.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn",
      "pages": 224,
      "title": "The Adventures of Huckleberry Finn",
      "year": 1884,
      "id": "4t4kcXXInDum_Vn5z4pI7KVjZX6pIdpw"
   },
   {
      "author": "Valmiki",
      "country": "India",
      "imageLink": "images/ramayana.jpg",
      "language": "Sanskrit",
      "link": "https://en.wikipedia.org/wiki/Ramayana",
      "pages": 152,
      "title": "Ramayana",
      "year": -450,
      "id": "Qt7vBaN5Y9zcP0tHp82Bw_1qYp8Xsu2v"
   },
   {
      "author": "Virgil",
      "country": "Roman Empire",
      "imageLink": "images/the-aeneid.jpg",
      "language": "Classical Latin",
      "link": "https://en.wikipedia.org/wiki/Aeneid",
      "pages": 442,
      "title": "The Aeneid",
      "year": -23,
      "id": "A1FVQeBWDh5yy0LYZ5z5y2jGJwrHfY6i"
   },
   {
      "author": "Vyasa",
      "country": "India",
      "imageLink": "images/the-mahab-harata.jpg",
      "language": "Sanskrit",
      "link": "https://en.wikipedia.org/wiki/Mahabharata",
      "pages": 276,
      "title": "Mahabharata",
      "year": -700,
      "id": "be11W34i36XnPgMx2r7IjJZTOm4fsOWi"
   },
   {
      "author": "Walt Whitman",
      "country": "United States",
      "imageLink": "images/leaves-of-grass.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Leaves_of_Grass",
      "pages": 152,
      "title": "Leaves of Grass",
      "year": 1855,
      "id": "mwFqDKj9g8cCgoS12EaWUtjNsFejhGRS"
   },
   {
      "author": "Virginia Woolf",
      "country": "United Kingdom",
      "imageLink": "images/mrs-dalloway.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Mrs_Dalloway",
      "pages": 216,
      "title": "Mrs Dalloway",
      "year": 1925,
      "id": "dST9kSLVkhy6AL_qnkxWsEJE36wf3v30"
   },
   {
      "author": "Virginia Woolf",
      "country": "United Kingdom",
      "imageLink": "images/to-the-lighthouse.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/To_the_Lighthouse",
      "pages": 209,
      "title": "To the Lighthouse",
      "year": 1927,
      "id": "H9L9ACVre6KtDewv7R41UbyW1Yo1HIq2"
   },
   {
      "author": "Marguerite Yourcenar",
      "country": "France/Belgium",
      "imageLink": "images/memoirs-of-hadrian.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian",
      "pages": 408,
      "title": "Memoirs of Hadrian",
      "year": 1951,
      "id": "KLMocythXd_HBHnurV7r_ERYWqpt__4Z"
   }
]